# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    
    - name: Npm build
      run: |
        npm install
        npm ci
        npm run build
    - name: Prepare for commit
      run: |
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "github-actions"
        cd dist
        git init
    - name: Commit deploy
      run: |
        git add -A
        git commit -m 'Deploy to github pages'
        git push -f https://matt-hu:${{ secrets.GITHUB_TOKEN }}@github.com/matt-hu/WebThrottle-EX.git master:gh-pages
    
      
