# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    
    - name: Npm build
      run: npm build
    - name: Prepare for commit
      run: |
        cd dist
        git init
    
    - name: Commit build
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: "Deploy from release"
      
